apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pdry4pw5g-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pdry4pw5g-python 
  name: pdry4pw5g-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pdry4pw5g-python 
